openapi: 3.0.1
info:
  title: VSCodeExc
  description: API Definition of VSCodeExc
  version: 1.0.0
servers:
- url: http://localhost:8290/vscodeexc
paths:
  /:
    get:
      responses:
        default:
          description: Default response
